export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    PROFILE: '/auth/profile',
    LOGOUT: '/auth/logout',
  },
  NEWS: '/news',
  PROGRAMS: '/programs',
  PROJECTS: '/projects',
  SPECIES: '/species',
  EVENTS: '/events',
  RESOURCES: '/resources',
  LIBRARY: '/resources',
  GALLERY: '/gallery',
  VOLUNTEERS: '/volunteers',
  DONATIONS: '/donations',
  IMPACT: '/impact',
  AI: {
    ASSISTANT: '/ai/assistant',
    IDENTIFY: '/ai/identify',
    RECOMMEND: '/ai/recommend',
    SEARCH: '/ai/search',
    TRANSLATE: '/ai/translate',
    SUMMARIZE: '/ai/summarize',
    CERTIFICATE: '/ai/certificate',
    IMPACT_REPORT: '/ai/impact/report',
  },
  EIS: {
    TUTOR: '/eis/tutor/ask',
    SPECIES_V2: '/eis/species-v2',
    OBSERVATORY: '/eis/observatory/observations',
    OBSERVATORY_MAP: '/eis/observatory/map',
    OBSERVATORY_STATS: '/eis/observatory/stats',
    KNOWLEDGE: '/eis/knowledge-base/entries',
    KNOWLEDGE_STATS: '/eis/knowledge-base/stats',
    ACTIVITIES_PLAN: '/eis/activities/plan',
    ACTIVITIES_RECOMMEND: '/eis/activities/recommendations',
    DOCUMENTS_ANALYZE: '/eis/documents/analyze-text',
    VALIDATE: '/eis/validate/response',
  },
} as const;

export const STORAGE_KEYS = {
  TOKEN: 'auth_token',
  REFRESH_TOKEN: 'auth_refresh_token',
  USER: 'auth_user',
  SETTINGS: 'app_settings',
  OFFLINE_QUEUE: 'offline_sync_queue',
  OBSERVATION_DRAFTS: 'observation_drafts',
  FAVORITES: 'favorites',
  DOWNLOADED_CONTENT: 'downloaded_content',
  GAMIFICATION: 'gamification_profile',
} as const;

export const CONFIG = {
  API_TIMEOUT: 15000,
  MAX_RETRIES: 3,
  SYNC_INTERVAL: 30000,
  PAGE_SIZE: 20,
  CACHE_TTL: 5 * 60 * 1000,
  MAX_OFFLINE_IMAGES: 50,
} as const;
