apiVersion: v1
kind: ConfigMap
metadata:
  name: sh-global-config
  namespace: sembrando-huellas-prod
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://sembrandohuellas.pe,https://admin.sembrandohuellas.pe"
  REDIS_HOST: "sh-redis-service"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "sh-minio-service"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: sh-global-secrets
  namespace: sembrando-huellas-prod
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sh_prod_user:SecurePass2026!@sh-postgres-service:5432/sembrando_huellas_prod?schema=public"
  JWT_SECRET: "e9a71f08c3d24e1b8b2e5c9f1a0b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b"
  REDIS_PASSWORD: "SuperSecretRedisPassword2026!"
  MINIO_ROOT_USER: "sh_admin_storage"
  MINIO_ROOT_PASSWORD: "SuperSecretMinioPassword2026!"
  AI_OPENAI_KEY: "sk-proj-placeholder-key"
  AI_ANTHROPIC_KEY: "sk-ant-placeholder-key"
  AI_GEMINI_KEY: "AIzaSyPlaceholderKey"
